"""adjusted added createdat

Revision ID: cfc93655fe21
Revises: eba2469cf422
Create Date: 2020-12-31 03:46:47.543893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfc93655fe21'
down_revision = 'eba2469cf422'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('comments', sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'createdAt')
    op.drop_column('activities', 'createdAt')
    # ### end Alembic commands ###
