"""users table

Revision ID: 258e9ab84187
Revises: 
Create Date: 2020-12-28 17:13:59.305298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '258e9ab84187'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=35), nullable=False),
    sa.Column('last_name', sa.String(length=35), nullable=False),
    sa.Column('city', sa.String(length=85), nullable=True),
    sa.Column('country', sa.String(length=75), nullable=True),
    sa.Column('avatar', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
